name: Compress Files

# Run the workflow on every push to the repository
on:
  push:
    branches:
      - main  # or your specific branch name

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository's contents
      - name: Checkout code
        uses: actions/checkout@v3

      # Upload the compressed file as an artifact for sharing
      - name: Upload compressed file
        uses: actions/upload-artifact@v3
        with:
          name: youtube-watch-counter
          path: ./
